_schema: _schema
# Include .git folder for POSSE integration git operations
include_git_folder: true
paths:
  uploads: uploads
  static: ""
  collections: ""
  data: ""
  layouts:
collections_config:
  notes:
    path: src/content/note
    icon: notes
    output: true
    url: /note/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      author:
        type: auto
        cascade: true
        empty_type: string
      tags:
        type: multiselect
        cascade: true
        allow_create: true
        empty_type: array
    add_options:
      - name: Add New Note
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/note.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Note
        icon: notes
  posts:
    path: src/content/blog
    icon: notes
    output: true
    url: /blog/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      author:
        type: auto
        cascade: true
        empty_type: string
      tags:
        type: multiselect
        cascade: true
        allow_create: true
        empty_type: array
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  drafts:
    path: src/content/draft
    icon: notes
    output: false
    url: /blog/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      author:
        type: auto
        cascade: true
        empty_type: string
      tags:
        type: multiselect
        cascade: true
        allow_create: true
        empty_type: array
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  ephemera:
    path: src/content/ephemera
    icon: notes
    output: true
    url: /ephemera/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      date:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      syndication:
        type: array
        cascade: true
        empty_type: array
        items:
          type: object
          properties:
            href:
              type: url
              label: URL
              comment: The URL of the syndicated post
            title:
              type: string
              label: Platform
              comment: Name of the platform (e.g., Mastodon, Bluesky)
    add_options:
      - name: Add New Ephemera
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/ephemera.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Ephemera
        icon: notes
  pages:
    path: src/pages
    icon: wysiwyg
    output: true
    url: /[slug]
    filter:
      base: strict
    _enabled_editors:
      - visual
    _inputs:
      content_blocks:
        type: auto
        cascade: true
        empty_type: array
    add_options:
      - name: Add New Page
        icon: note_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Page
        icon: notes
        new_preview_url: /
      paginated_collection:
        path: schemas/paginated-collection.md
        reorder_inputs: true
        hide_extra_inputs: false
         remove_empty_inputs: false
         remove_extra_inputs: true
         icon: notes
collection_groups:
  - heading: Content
    collections:
      - posts
      - notes
      - ephemera
  - heading: Pages
    collections:
      - pages
  - heading: Drafts
    collections:
      - drafts
timezone: America/New_York
