_schema: _schema
paths:
  uploads: uploads
  static: ""
  collections: ""
  data: ""
  layouts:
collections_config:
  notes:
    path: src/content/note
    glob:
      - "!**/index.md"
      - "!**/_index.md"
    icon: notes
    output: true
    url: /note/[slug]
    preview:
      text:
        - key: title
      subtext:
        - "Updated: "
        - key: updatedDate
        - key: tags
    sort:
      key: updatedDate
      order: desc
    _inputs:
      title:
        type: string
        label: Title
        cascade: true
        empty_type: string
      description:
        type: text
        label: Description
        cascade: true
        empty_type: string
      pubDate:
        type: datetime
        label: Publication Date
        cascade: true
      updatedDate:
        type: datetime
        label: Last Updated
        cascade: true
      categories:
        type: multiselect
        label: Categories
        cascade: true
        allow_create: true
        empty_type: array
      tags:
        type: multiselect
        label: Tags
        cascade: true
        allow_create: true
        empty_type: array
      featured:
        type: boolean
        label: Featured
        cascade: true
    add_options:
      - name: Add New Note
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/note.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Note
        icon: notes
  posts:
    path: src/content/blog
    glob:
      - "!**/index.md"
      - "!**/_index.md"
    icon: notes
    output: true
    url: /blog/[slug]
    preview:
      text:
        - key: title
        - key: description
      subtext:
        - "Published: "
        - key: pubDate
        - key: tags
      image: thumb_image.image
    sort:
      key: pubDate
      order: desc
    _inputs:
      title:
        type: string
        label: Title
        cascade: true
        empty_type: string
      description:
        type: text
        label: Description
        cascade: true
        empty_type: string
      pubDate:
        type: datetime
        label: Publication Date
        cascade: true
      updatedDate:
        type: datetime
        label: Last Updated
        cascade: true
      categories:
        type: multiselect
        label: Categories
        cascade: true
        allow_create: true
        empty_type: array
      tags:
        type: multiselect
        label: Tags
        cascade: true
        allow_create: true
        empty_type: array
      featured:
        type: boolean
        label: Featured
        cascade: true
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  drafts:
    path: src/content/draft
    icon: notes
    output: false
    url: /blog/[slug]
    _inputs:
      title:
        type: string
        label: Title
        cascade: true
        empty_type: string
      description:
        type: text
        label: Description
        cascade: true
        empty_type: string
      pubDate:
        type: datetime
        label: Publication Date
        cascade: true
      updatedDate:
        type: datetime
        label: Last Updated
        cascade: true
      categories:
        type: multiselect
        label: Categories
        cascade: true
        allow_create: true
        empty_type: array
      tags:
        type: multiselect
        label: Tags
        cascade: true
        allow_create: true
        empty_type: array
      featured:
        type: boolean
        label: Featured
        cascade: true
      no_index:
        type: boolean
        label: No Index
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  ephemera:
    path: src/content/ephemera
    glob:
      - "!**/index.md"
      - "!**/_index.md"
    icon: notes
    output: true
    url: /ephemera/[slug]
    _inputs:
      date:
        type: datetime
        label: Publication Date
        cascade: true
      syndication:
        type: array
        label: Syndication Links
        cascade: true
        empty_type: array
        structures:
          - name: Syndication Link
            icon: link
            fields:
              href:
                type: url
                label: URL
                comment: The URL of the syndicated post
              title:
                type: string
                label: Platform
                comment: Name of the platform (e.g., Mastodon, Bluesky)
      youtube:
        type: url
        label: YouTube URL
        cascade: true
        empty_type: string
      image:
        type: file
        label: Image
        cascade: true
        empty_type: string
      image_alt:
        type: string
        label: Image Alt Text
        cascade: true
        empty_type: string
    add_options:
      - name: Add New Ephemera
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/ephemera.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Ephemera
        icon: notes

collection_groups:
  - heading: Content
    collections:
      - posts
      - notes
      - ephemera
  - heading: Pages
    collections:
      - pages
  - heading: Drafts
    collections:
      - drafts

_inputs:
  author:
    type: select
    options:
      allow_empty: true
      values:
        - Ryan Parsley
    label: Author
    cascade: true
  tags:
    type: multiselect
    options:
      empty_type: array
      values:
        - posse
        - indieWeb
        - typeScript
        - astro
        - music
        - lsdj
        - neovim
        - vim
        - code
        - dotfiles
        - digitalGarden
        - 3DPrint
        - diy
    label: Tags
    cascade: true
    allow_create: true
  categories:
    type: multiselect
    options:
      empty_type: array
      values:
        - code
        - music
        - writing
    label: Categories
    cascade: true
    allow_create: true
  updatedDate:
    type: datetime
    label: Last Updated
    cascade: true
    default: "[date]"

base_url: /
data_config:
  navigation:
    path: data/navigation.yml
timezone: America/New_York
build:
  cache:
    - node_modules
    - .astro
  command: npm run build
include_git_folder: true
