_schema: _schema
paths:
  uploads: uploads
  static: ""
  collections: ""
  data: ""
  layouts:
# Include .git folder for SYNC_PATHS to work
include_git_folder: true
# POSSE syndication - automatically commit changes to ephemera posts
SYNC_PATHS: src/content/ephemera/
collections_config:
  notes:
    path: src/content/note
    icon: notes
    output: true
    url: /note/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      author:
        type: auto
        cascade: true
        empty_type: string
      tags:
        type: multiselect
        cascade: true
        allow_create: true
        empty_type: array
    add_options:
      - name: Add New Note
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/note.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Note
        icon: notes
  posts:
    path: src/content/blog
    icon: notes
    output: true
    url: /blog/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      author:
        type: auto
        cascade: true
        empty_type: string
      tags:
        type: multiselect
        cascade: true
        allow_create: true
        empty_type: array
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  drafts:
    path: src/content/draft
    icon: notes
    output: false
    url: /blog/[slug]
    _inputs:
      title:
        type: auto
        cascade: true
        empty_type: string
      image:
        type: auto
        cascade: true
        empty_type: string
      image_alt:
        type: auto
        cascade: true
        empty_type: string
      author:
        type: auto
        cascade: true
        empty_type: string
      tags:
        type: multiselect
        cascade: true
        allow_create: true
        empty_type: array
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  pages:
    path: src/content/page
    icon: wysiwyg
    output: true
    url: /[slug]
    filter:
      base: strict
    _enabled_editors:
      - visual
    _inputs:
      content_blocks:
        type: auto
        cascade: true
        empty_type: array
    add_options:
      - name: Add New Page
        icon: note_add
        schema: default
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Page
        icon: notes
        new_preview_url: /
      paginated_collection:
        path: schemas/paginated-collection.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
timezone: America/New_York
