# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - name: Cache Astro build
        uses: actions/cache@v3
        with:
          path: .astro
          key: astro-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            astro-${{ runner.os }}-
      - run: npm run build
      - run: npm run test:run
